
documents = [
    {"title": "R1 Short title, applicability and commencement", "link": "https://docs.google.com/document/d/1X-TEUSA3of06h0FEpTRp-0X6Q6Ial9um/edit"},
    {"title": "R2 Definitions", "link": "https://docs.google.com/document/d/1Uv2xo-C0Uv5qy74MS6gOkXzY3lBx85HF/edit"},
    {"title": "R3 Applicability", "link": "https://docs.google.com/document/d/1JUCUI1Z7k1_SxIvZR1k4Ez_97vjP3zbU/edit"},
    {"title": "R4 DRAWINGS, PERMITS AND OCCUPANCY CERTIFICATES", "link": "https://docs.google.com/document/d/1rQoJmBRa8aK3Q1Y2oAM43_7-lHEkzi4j/edit"},
    {"title": "R5 Application for development / building permit", "link": "https://docs.google.com/document/d/1UtQeXhJ0HiyuDSfM2Im0OiEqnSPj90v6/edit"},
    {"title": "R6 Plans to be submitted", "link": "https://docs.google.com/document/d/1vCCNztAimcQQCxqUNVHA-2sGvqpW2J7u/edit"},
    {"title": "R7 Certain operational constructions by Government to be exempted from these rules", "link": "https://docs.google.com/document/d/19SlPVnOvx_sLVa1vGkQcgQRtZlCZX2Wh/edit"},
    {"title": "R8 Permit not necessary for certain works", "link": "https://docs.google.com/document/d/1KAbVJwaUZNubHNqBwhfeSQsPqiocm9h-/edit"},
    {"title": "R9 Approval of site and plans and issue of permit", "link": "https://docs.google.com/document/d/1g6vgoejoRhiWKGX8WgbA5cx04HFUEIdd/edit"},
    {"title": "R10 Approval of site and plans and issue of permit where excavations to a depth of more than 1.5M", "link": "https://docs.google.com/document/d/1cJGq_dg4uhAaShImJXA9_jRb-gLiajaP/edit"},

    {"title": "R11 Grounds on which approval of site or permission to construct or reconstruct building may be rejected", "link": "https://docs.google.com/document/d/1z3mtHghA8ZJ115NE13M1etKVVh19a9Hv/edit"},
    {"title": "R12 Period within which approval or disapproval shall be intimated", "link": "https://docs.google.com/document/d/1M5VlLEfJouO2nFjnqN7G1jJrAdydYI6e/edit"},
    {"title": "R13 Period within which Secretary is to grant or refuse permission to execute work", "link": "https://docs.google.com/document/d/1g1kylyGEMPrMmMWxy_TrOGFXngPWzMcc/edit"},
    {"title": "R14 Reference to Council where the Secretary delays to grant or refuse or approve permit", "link": "https://docs.google.com/document/d/1PJnWQY97zS8eWrtY2CNXLSHxGDrV54u4/edit"},
    {"title": "R15 Extension and renewal of period of permits", "link": "https://docs.google.com/document/d/1bRVdr4HHoKati1m7dYZiPXuc1LABq6i8/edit"},
    {"title": "R16 Suspension and Revocation of permit", "link": "https://docs.google.com/document/d/1iBo0gs_WFhk9PtYseXlgGNogkEKqoGnD/edit"},
    {"title": "R17 Duties and responsibilities of the owner or developer", "link": "https://docs.google.com/document/d/1XgOs2Kt6Po6dh7PSGy-D4DjGZjQ_-OT7/edit"},
    {"title": "R18 Responsibilities and functions of registered Architects, etc", "link": "https://docs.google.com/document/d/1oeyx6B5gn-CW1fZ4bHAs6PaoLQ9p__xV/edit"},
    {"title": "R19 Transfer of plots to be intimated", "link": "https://docs.google.com/document/d/1Ur-ZjE_CTsQC4004vUW5MeQiMLodqr7Z/edit"},
    {"title": "R19A Procedure for grant of acknowledgement certificate", "link": "https://docs.google.com/document/d/1sLH9f_Kq9M-LtfqiXY3UpNocHfrMHDuE/edit"},
    {"title": "R19B Other conditions pertaining to self certification", "link": "https://docs.google.com/document/d/1T9ucyEr92RYpQMkGWcbtOiL2HjgV9i_I/edit"},
    {"title": "R19C Issue of occupancy certificate", "link": "https://docs.google.com/document/d/1ELknFVL479VN3tzvcDxRt19ujZovtcEE/edit"},
    {"title": "R19D Procedure for plinth level inspection for low-risk buildings", "link": "https://docs.google.com/document/d/11xZ9bil_CbZuTUnnldKy8eQRKxP9nHi6/edit"},
    {"title": "R19E Procedure for plinth level inspection for all other buildings", "link": "https://docs.google.com/document/d/1QB21Ub6dXHScOMGhdVuun5grfsC1Ucpy/edit"},
    {"title": "R19F Deemed completion of plinth level inspection", "link": "https://docs.google.com/document/d/1zEulx7AOD6fmM1STR-kc877OgL4A8Ba0/edit"},
    {"title": "R20 Completion report, development certificate and occupancy certificate",
     "link": "https://docs.google.com/document/d/1SMZB6aoJXwYjAbwUNXZLCsGr9uSsB6yB/edit"},
    {"title": "R21 Post Occupancy Audit",
     "link": "https://docs.google.com/document/d/14O5zEQwLLYuSdhF4lxtk-HlvnCpGToWp/edit"},
    {"title": "R22 GENERAL PROVISIONS REGARDING SITE AND BUILDING REQUIREMENTS",
     "link": "https://docs.google.com/document/d/1HtzOorE-NZqdYYAp7jgKJ0H5COv0Cxxh/edit"},
    {"title": "R23 Prohibition for constructions abutting public roads/streets",
     "link": "https://docs.google.com/document/d/1xf1uD59nJsgtlYkYBAWhNa-IPtle-5xx/edit"},
  {"title": "R24 Height of buildings",
     "link": "https://docs.google.com/document/d/1VzYL4GSNrpHlpk06BtFN-l1JWoGWHE8H/edit"},
    {"title": "R25 OCCUPANCY", "link": "https://docs.google.com/document/d/12jF89VKATVw4D0DaYNBDE5tLlY8EMiYM/edit"},
    {"title": "R26 Exterior and Interior open air spaces",
     "link": "https://docs.google.com/document/d/15-TRtv1vdD0mQ246_FOPJEsxkk6CXENW/edit"},
    {"title": "R27 Coverage and Floor Space Index",
     "link": "https://docs.google.com/document/d/1UxlEhLEiflveKGlgupE197MXdlBzJfcF/edit"},
    {"title": "R28 Access", "link": "https://docs.google.com/document/d/1Kh8zL4ibzgEFkdmZIYnt_T_Xc1ahZVtG/edit"},
    {"title": "R29 Parking, loading and unloading spaces",
     "link": "https://docs.google.com/document/d/1ggunqzLRNzsyVePjRdrubjiYjcyUKbmw/edit"},
    {"title": "R30 Approval for layout of buildings and usage of plot",
     "link": "https://docs.google.com/document/d/1UXhRhXOicdVclUu2ufzn64tv_otwpW5C/edit"},
    {"title": "R31 Land sub-division and plot development",
     "link": "https://docs.google.com/document/d/1EwGlNOKEqwInGeKznSZPyzzFoGpxfgxF/edit"},
    {"title": "R32 Mezzanine floor - PARTS OF BUILDING",
     "link": "https://docs.google.com/document/d/1_IETu-bvCb0kaF3SWb22_PDdaKcCp86K/edit"},
    {"title": "R33 Height of room",
     "link": "https://docs.google.com/document/d/1LknqDg2GvJCoSKehv6Zj39RuQ7vGId6k/edit"},
    {"title": "R34 Sanitation Facilities",
     "link": "https://docs.google.com/document/d/1uTECU6L0WWM7oO67h8Ie1e4F6H3K6H6j/edit"},
    {"title": "R35 Staircases and fire escape staircases",
     "link": "https://docs.google.com/document/d/13tot9LEhtqbaOiCMDIiwYzMqbWT9jXwA/edit"},
    {"title": "R36 Travel distance to emergency exit",
     "link": "https://docs.google.com/document/d/1NxGV6176LajOy6qcqUDkBhxA_Wy8IYSg/edit"},
    {"title": "R37 Exit Width", "link": "https://docs.google.com/document/d/1FdWQeH_JFOapWy2hFEefbPDVKdHOoCt8/edit"},
    {"title": "R38 Doorways", "link": "https://docs.google.com/document/d/16BZcI7r3yU8diq-dJAnFl8SWYZw3vWDM/edit"},
    {"title": "R39 Corridor, verandahs and passageways",
     "link": "https://docs.google.com/document/d/1hh1gTOorX3RIUNMblGCWIBVXB8V3I_Gm/edit"},
    {"title": "R40 Lift /Escalator",
     "link": "https://docs.google.com/document/d/1uCVxY_mhQJeZJu-juf_ttO5A3vm17l3X/edit"},
    {"title": "R41 Lighting and Ventilation",
     "link": "https://docs.google.com/document/d/1M-xvwv2bTnb8619dqtvw3q3_ntwAEAjj/edit"},
    {"title": "R41A In-building Solutions",
     "link": "https://docs.google.com/document/d/1vrVsm50kANj_wv0esdSbGB-Rv94JmwNH/edit"},
    {"title": "R42 Differently-abled, Elderly and Children",
     "link": "https://docs.google.com/document/d/1Ht-8jNJV1gUD8Q0JADe0-kwYBkaZpXfN/edit"},
    {"title": "R43 Group A1 Residential occupancy",
     "link": "https://docs.google.com/document/d/1r0dWblkKUhp51uwmhc11NHzGH4JTCi2K/edit"},
    {"title": "R44 Group D Assembly Occupancy",
     "link": "https://docs.google.com/document/d/1yrjFJtqxt9_prIEDCyfw6Hg2IBUdpCdx/edit"},
    {"title": "R45 Group G1 and G2 industrial occupancy",
     "link": "https://docs.google.com/document/d/1sYN-Mk8ULp-CQtxeZwdFOZCuVXRhFVXH/edit"},
    {"title": "R46 Group H Storage occupancy",
     "link": "https://docs.google.com/document/d/1xw__E8dXqXzOJh29Inr0WpDj_yc5aed0/edit"},
    {"title": "R47 Group I Hazardous occupancy",
     "link": "https://docs.google.com/document/d/1RQkJ4AS-P-g2fez1GPHTCDlD_Wo_LeQb/edit"},
    {"title": "R48 Certain Buildings exempted",
     "link": "https://docs.google.com/document/d/1Sw89agXJ0obEz0N6a0HyjQVGM9qK7LNH/edit"},
{"title": "R49 HUTS AND BUILDINGS IN SMALL PLOTS", "link": "https://docs.google.com/document/d/11lD2JxT3sbp7Pqmll7TsKnHMv1xr_rev/edit?usp=drive_link"},
{"title": "R50 construction in small plots", "link": "https://docs.google.com/document/d/1u6RilJrQUkimeQkUVo0hripeNctNUe5D/edit?usp=drive_link"},
{"title": "R51 ROW BUILDINGS", "link": "https://docs.google.com/document/d/1BqYcH1qEdAdJqxCDqWR3WAIi0SwtlcPR/edit?usp=drive_link"},
{"title": "R52 APPROVED SCHEMES", "link": "https://docs.google.com/document/d/1kjM3EUcF2VbkYp__GyAH7K0ZBIbsWmGJ/edit?usp=drive_link"},
{"title": "R53 Area and floor restrictions", "link": "https://docs.google.com/document/d/18XNqZ4o5tudBnRjmvhtQ1OnsdK4TWoyj/edit?usp=drive_link"},
{"title": "R54 Setback provisions", "link": "https://docs.google.com/document/d/1e4xP2Rs1YrEk_3dNLYRGQjg4Xou1J1Xj/edit?usp=drive_link"},
{"title": "R55 Certain provisions not to apply", "link": "https://docs.google.com/document/d/1JJe-lSkc0a36Qk3dXIve09cvNK6MrC88/edit?usp=drive_link"},
{"title": "R56 Application for permit and its disposal", "link": "https://docs.google.com/document/d/1qMeOE5sGCk3tNIxbJQjlaJhFvvivQVHX/edit?usp=drive_link"},
{"title": "R57 LARGE-SCALE DEVELOPMENT PROJECTS", "link": "https://docs.google.com/document/d/1ixRVj0BLdyE4YT-oLpWuj7xt9cd98NHb/edit?usp=drive_link"},
{"title": "R58 Constitution and functioning of the committee", "link": "https://docs.google.com/document/d/1uduQ4aaWGlhHlBDUgDYWm-ZBQxL6m_0f/edit?usp=drive_link"},
{"title": "R59 Provision for supporting infrastructure", "link": "https://docs.google.com/document/d/1vcZnC5HNOjk0Y2LSusFnMqQaxNEYwM6P/edit?usp=drive_link"},
{"title": "R60 Memorandum of Understanding", "link": "https://docs.google.com/document/d/1qz5NipvVMMSdp9YZXqZsvYYDbthLV7xK/edit?usp=drive_link"},
{"title": "R61 The F.S.I. permissible for the project", "link": "https://docs.google.com/document/d/1T2OTB8jgI_AOMNX30Ye6MEy-AhjpC-L3/edit?usp=drive_link"},
{"title": "R62 SURRENDERED FREE OF COST FOR ROAD DEVELOPMENT", "link": "https://docs.google.com/document/d/1mYMVrYUQCGuja_8WpclrdHo7tv_VhLwy/edit?usp=drive_link"},
{"title": "R63 Usage of Plot", "link": "https://docs.google.com/document/d/11-y_Sml3x7z2_TWfyLJ0L-UtrP0xdXvO/edit?usp=drive_link"},
{"title": "R64 Coverage and Floor Space Index", "link": "https://docs.google.com/document/d/1Rp_42mn96R46-0-LzkHkjJUmV0glsOP8/edit?usp=drive_link"},
{"title": "R65 Constitution of Special Committees", "link": "https://docs.google.com/document/d/1jSPWTeqK2IMYqBU4j7E99pyHIyMfH1PV/edit?usp=drive_link"},
{"title": "R66 Demolished for the purposes specified in rule 62", "link": "https://docs.google.com/document/d/1ykwMmtf_DtTaKa7J2h5GgVRvrcRWC5GT/edit?usp=drive_link"},
{"title": "R67 ACCESSORY BUILDINGS AND SHED", "link": "https://docs.google.com/document/d/10Hd2nfYJ16iZIJ9J7pTyg1XoMjDHh_wI/edit?usp=drive_link"},
{"title": "R68 Temporary hut or shed", "link": "https://docs.google.com/document/d/1h-11mDMUxqdn8XiUtI-px1rN_QQmHrjB/edit?usp=drive_link"},
{"title": "R69 WALL AND FENCE", "link": "https://docs.google.com/document/d/139f3_EUdARSpKQI4G--rDYJ-E1VWnlL8/edit?usp=drive_link"},
{"title": "R70 Submission and disposal of application", "link": "https://docs.google.com/document/d/1xoIJrxpNdBNU5cvCMZptkoGyTq9pVqxb/edit?usp=drive_link"},
{"title": "R71 Completion report", "link": "https://docs.google.com/document/d/1ceDe1sQdF7115evvlZXWfVUg6QaQRC5j/edit?usp=drive_link"},
{"title": "R72 CHAPTER XIII - SPECIAL PROVISIONS FOR CERTAIN CONSTRUCTIONS", "link": "https://docs.google.com/document/d/1NNMlo9dulDnxbWDCaQLAnL-cdRpUcvDx/edit?usp=drive_link"},
{"title": "R73 Conversion of roof, shutters etc. of buildings existing before the commencement of these rules", "link": "https://docs.google.com/document/d/1UVQZfDFnJCppWmGkFrt2lDribkbbTx21/edit?usp=drive_link"},
{"title": "R74 Construction of additional sheet/tiled roof over the terrace of certain single-family residential building", "link": "https://docs.google.com/document/d/1FltaOUicTM9ZnYeldStDCaViOqpFt_nA/edit?usp=drive_link"},
{"title": "R75 WELLS, RAINWATER HARVESTING", "link": "https://docs.google.com/document/d/1E12kmrWUmUkYMlpNuKOSn0HNaQUS8nNm/edit?usp=drive_link"},
{"title": "R76 Rain water harvesting", "link": "https://docs.google.com/document/d/19CYGvz2RBS1jOlk98OE2FqwSa-Y0waSj/edit?usp=drive_link"},
{"title": "R77 SOLAR ASSISTED WATER HEATING/LIGHTING SYSTEM", "link": "https://docs.google.com/document/d/1uSuM6WMt5W61bRK60E3R3-t4a7Ny7zIj/edit?usp=drive_link"},
{"title": "R79 WASTE DISPOSAL", "link": "https://docs.google.com/document/d/1x2uSRVoZBs-pCjp-vz012joGQsNk2YMW/edit?usp=drive_link"},
{"title": "R79A Management of Construction and Demolition Waste", "link": "https://docs.google.com/document/d/1xXoJIMITwhA7moUNP34j7bifiAfkXGxM/edit?usp=drive_link"},
{"title": "R80 HIGHRISE BUILDINGS", "link": "https://docs.google.com/document/d/1mspsjBNGbuSOxBc0NajgfgpHEE_8lQyW/edit?usp=drive_link"},
{"title": "R81 Safety provisions", "link": "https://docs.google.com/document/d/1JQ4pdcDcsIQjXLUB2-xKl2hFcONtfRSw/edit?usp=drive_link"},
{"title": "R82 Display of the details of the permit etc", "link": "https://docs.google.com/document/d/1L5tDEA97GXhzhs6r6I_M0uzGRVrDLL7w/edit?usp=drive_link"},
{"title": "R83 TELECOMMUNICATION TOWERS", "link": "https://docs.google.com/document/d/1MlecwWqgyxik0a9stYeGhbCzxhCT6qTF/edit?usp=drive_link"},
{"title": "R84 Distance from road and boundaries", "link": "https://docs.google.com/document/d/1Q4KDF9ylHKGH_MmjV215EsQfQMCu5-r9/edit?usp=drive_link"},
{"title": "R85 Damage and liability", "link": "https://docs.google.com/document/d/1KE2HIOU1c8EgC9cOmEZNHnbHFYQamMzS/edit?usp=drive_link"},
{"title": "R86 Consent of airport authorities", "link": "https://docs.google.com/document/d/1uWHymS41amReODJcOgH-Fm77KwgnZomF/edit?usp=drive_link"},
{"title": "R87 NATIONAL BUILDING CODE", "link": "https://docs.google.com/document/d/1NVsFdcK4FbEpa7Duv9JFX-fAMJ9dyIKU/edit?usp=drive_link"},
{"title": "R88 CHAPTER XV - DISTRICT LEVEL COMMITTEE", "link": "https://docs.google.com/document/d/1Sn76Xg7MXUGfZgoDL9sySw0_gkhAZ1mD/edit?usp=drive_link"},
{"title": "R89 PROCEDURE FOR IMPLEMENTATION OF DEVELOPMENT PLANS", "link": "https://docs.google.com/document/d/1ODLzZbdbq3fEXfKNnoMD21XJTHXClKRH/edit?usp=drive_link"},
{"title": "R90 CHAPTER XVII- MISCELLANEOUS", "link": "https://docs.google.com/document/d/13iqJ_r3FY8HGcCBUTexfFTe4ov62vfzW/edit?usp=drive_link"},
{"title": "R49 HUTS AND BUILDINGS IN SMALL PLOTS", "link": "https://docs.google.com/document/d/11lD2JxT3sbp7Pqmll7TsKnHMv1xr_rev/edit?usp=drive_link"},
{"title": "R50 construction in small plots", "link": "https://docs.google.com/document/d/1u6RilJrQUkimeQkUVo0hripeNctNUe5D/edit?usp=drive_link"},
{"title": "R51 ROW BUILDINGS", "link": "https://docs.google.com/document/d/1BqYcH1qEdAdJqxCDqWR3WAIi0SwtlcPR/edit?usp=drive_link"},
{"title": "R52 APPROVED SCHEMES", "link": "https://docs.google.com/document/d/1kjM3EUcF2VbkYp__GyAH7K0ZBIbsWmGJ/edit?usp=drive_link"},
{"title": "R53 Area and floor restrictions", "link": "https://docs.google.com/document/d/18XNqZ4o5tudBnRjmvhtQ1OnsdK4TWoyj/edit?usp=drive_link"},
{"title": "R54 Setback provisions", "link": "https://docs.google.com/document/d/1e4xP2Rs1YrEk_3dNLYRGQjg4Xou1J1Xj/edit?usp=drive_link"},
{"title": "R55 Certain provisions not to apply", "link": "https://docs.google.com/document/d/1JJe-lSkc0a36Qk3dXIve09cvNK6MrC88/edit?usp=drive_link"},
{"title": "R56 Application for permit and its disposal", "link": "https://docs.google.com/document/d/1qMeOE5sGCk3tNIxbJQjlaJhFvvivQVHX/edit?usp=drive_link"},
{"title": "R57 LARGE-SCALE DEVELOPMENT PROJECTS", "link": "https://docs.google.com/document/d/1ixRVj0BLdyE4YT-oLpWuj7xt9cd98NHb/edit?usp=drive_link"},
{"title": "R58 Constitution and functioning of the committee", "link": "https://docs.google.com/document/d/1uduQ4aaWGlhHlBDUgDYWm-ZBQxL6m_0f/edit?usp=drive_link"},
{"title": "R59 Provision for supporting infrastructure", "link": "https://docs.google.com/document/d/1vcZnC5HNOjk0Y2LSusFnMqQaxNEYwM6P/edit?usp=drive_link"},
{"title": "R60 Memorandum of Understanding", "link": "https://docs.google.com/document/d/1qz5NipvVMMSdp9YZXqZsvYYDbthLV7xK/edit?usp=drive_link"},
{"title": "R61 The F.S.I. permissible for the project", "link": "https://docs.google.com/document/d/1T2OTB8jgI_AOMNX30Ye6MEy-AhjpC-L3/edit?usp=drive_link"},
{"title": "R62 SURRENDERED FREE OF COST FOR ROAD DEVELOPMENT", "link": "https://docs.google.com/document/d/1mYMVrYUQCGuja_8WpclrdHo7tv_VhLwy/edit?usp=drive_link"},
{"title": "R63 Usage of Plot", "link": "https://docs.google.com/document/d/11-y_Sml3x7z2_TWfyLJ0L-UtrP0xdXvO/edit?usp=drive_link"},
{"title": "R64 Coverage and Floor Space Index", "link": "https://docs.google.com/document/d/1Rp_42mn96R46-0-LzkHkjJUmV0glsOP8/edit?usp=drive_link"},
{"title": "R65 Constitution of Special Committees", "link": "https://docs.google.com/document/d/1jSPWTeqK2IMYqBU4j7E99pyHIyMfH1PV/edit?usp=drive_link"},
{"title": "R66 Demolished for the purposes specified in rule 62", "link": "https://docs.google.com/document/d/1ykwMmtf_DtTaKa7J2h5GgVRvrcRWC5GT/edit?usp=drive_link"},
{"title": "R67 ACCESSORY BUILDINGS AND SHED", "link": "https://docs.google.com/document/d/10Hd2nfYJ16iZIJ9J7pTyg1XoMjDHh_wI/edit?usp=drive_link"},
{"title": "R68 Temporary hut or shed", "link": "https://docs.google.com/document/d/1h-11mDMUxqdn8XiUtI-px1rN_QQmHrjB/edit?usp=drive_link"},
{"title": "R69 WALL AND FENCE", "link": "https://docs.google.com/document/d/139f3_EUdARSpKQI4G--rDYJ-E1VWnlL8/edit?usp=drive_link"},
{"title": "R70 Submission and disposal of application", "link": "https://docs.google.com/document/d/1xoIJrxpNdBNU5cvCMZptkoGyTq9pVqxb/edit?usp=drive_link"},
{"title": "R71 Completion report", "link": "https://docs.google.com/document/d/1ceDe1sQdF7115evvlZXWfVUg6QaQRC5j/edit?usp=drive_link"},
{"title": "R72 CHAPTER XIII - SPECIAL PROVISIONS FOR CERTAIN CONSTRUCTIONS", "link": "https://docs.google.com/document/d/1NNMlo9dulDnxbWDCaQLAnL-cdRpUcvDx/edit?usp=drive_link"},
{"title": "R73 Conversion of roof, shutters etc. of buildings existing before the commencement of these rules", "link": "https://docs.google.com/document/d/1UVQZfDFnJCppWmGkFrt2lDribkbbTx21/edit?usp=drive_link"},
{"title": "R74 Construction of additional sheet/tiled roof over the terrace of certain single-family residential building", "link": "https://docs.google.com/document/d/1FltaOUicTM9ZnYeldStDCaViOqpFt_nA/edit?usp=drive_link"},
{"title": "R75 WELLS, RAINWATER HARVESTING", "link": "https://docs.google.com/document/d/1E12kmrWUmUkYMlpNuKOSn0HNaQUS8nNm/edit?usp=drive_link"},
{"title": "R76 Rain water harvesting", "link": "https://docs.google.com/document/d/19CYGvz2RBS1jOlk98OE2FqwSa-Y0waSj/edit?usp=drive_link"},
{"title": "R77 SOLAR ASSISTED WATER HEATING/LIGHTING SYSTEM", "link": "https://docs.google.com/document/d/1uSuM6WMt5W61bRK60E3R3-t4a7Ny7zIj/edit?usp=drive_link"},
{"title": "R79 WASTE DISPOSAL", "link": "https://docs.google.com/document/d/1x2uSRVoZBs-pCjp-vz012joGQsNk2YMW/edit?usp=drive_link"},
{"title": "R79A Management of Construction and Demolition Waste", "link": "https://docs.google.com/document/d/1xXoJIMITwhA7moUNP34j7bifiAfkXGxM/edit?usp=drive_link"},
{"title": "R80 HIGHRISE BUILDINGS", "link": "https://docs.google.com/document/d/1mspsjBNGbuSOxBc0NajgfgpHEE_8lQyW/edit?usp=drive_link"},
{"title": "R81 Safety provisions", "link": "https://docs.google.com/document/d/1JQ4pdcDcsIQjXLUB2-xKl2hFcONtfRSw/edit?usp=drive_link"},
{"title": "R82 Display of the details of the permit etc", "link": "https://docs.google.com/document/d/1L5tDEA97GXhzhs6r6I_M0uzGRVrDLL7w/edit?usp=drive_link"},
{"title": "R83 TELECOMMUNICATION TOWERS", "link": "https://docs.google.com/document/d/1MlecwWqgyxik0a9stYeGhbCzxhCT6qTF/edit?usp=drive_link"},
{"title": "R84 Distance from road and boundaries", "link": "https://docs.google.com/document/d/1Q4KDF9ylHKGH_MmjV215EsQfQMCu5-r9/edit?usp=drive_link"},
{"title": "R85 Damage and liability", "link": "https://docs.google.com/document/d/1KE2HIOU1c8EgC9cOmEZNHnbHFYQamMzS/edit?usp=drive_link"},
{"title": "R86 Consent of airport authorities", "link": "https://docs.google.com/document/d/1uWHymS41amReODJcOgH-Fm77KwgnZomF/edit?usp=drive_link"},
{"title": "R87 NATIONAL BUILDING CODE", "link": "https://docs.google.com/document/d/1NVsFdcK4FbEpa7Duv9JFX-fAMJ9dyIKU/edit?usp=drive_link"},
{"title": "R88 CHAPTER XV - DISTRICT LEVEL COMMITTEE", "link": "https://docs.google.com/document/d/1Sn76Xg7MXUGfZgoDL9sySw0_gkhAZ1mD/edit?usp=drive_link"},
{"title": "R89 PROCEDURE FOR IMPLEMENTATION OF DEVELOPMENT PLANS", "link": "https://docs.google.com/document/d/1ODLzZbdbq3fEXfKNnoMD21XJTHXClKRH/edit?usp=drive_link"},
{"title": "R90 CHAPTER XVII- MISCELLANEOUS", "link": "https://docs.google.com/document/d/13iqJ_r3FY8HGcCBUTexfFTe4ov62vfzW/edit?usp=drive_link"},
{"title": "R91 Appeals", "link": "https://docs.google.com/document/d/1TF9vYyY-Q0LMtJWwH4_Ut1Eep17_wNV9/edit?usp=drive_link"},
{"title": "R92 Penalty for violation", "link": "https://docs.google.com/document/d/1DWEwy5POkZ1HQ6lqHnWfsE4_v3xUutLO/edit?usp=drive_link"},
{"title": "R93 Action by authority", "link": "https://docs.google.com/document/d/1dJh39VInr-cZ26WcJz_kqIJF-oy7-OsL/edit?usp=drive_link"},
{"title": "R94 Power to make regulations", "link": "https://docs.google.com/document/d/1t5hSDS0wBzpA8FgHkym25be_54GS7KXj/edit?usp=drive_link"},
{"title": "R95 Repeal", "link": "https://docs.google.com/document/d/1BNj-x3GgR8K4q4Eau44SjRmyUez8UPqV/edit?usp=drive_link"},
{"title": "R97 Power to clarify", "link": "https://docs.google.com/document/d/1gsW2vD0jpdm1enFTY-McfggN6Yz9F0sS/edit?usp=drive_link"},
{"title": "R98 Penalty for obstructing the enforcement", "link": "https://docs.google.com/document/d/1YcsmYhhIen69Dd5g4V94xGf_JHY_uSn2/edit?usp=drive_link"},
{"title": "R99 Rules for construction and land use", "link": "https://docs.google.com/document/d/1B6fLjpaAhW8VnL-y-IBFk4V5WlD-_Hps/edit?usp=drive_link"},
{"title": "R100 Procedure for disposal of complaints", "link": "https://docs.google.com/document/d/1EFk_rqa68IV8E1wG_wK3pVsLSyEdNUFZ/edit?usp=drive_link"},
{"title": "R101 Code of conduct for employees", "link": "https://docs.google.com/document/d/1WcF-8Tf1x-tNfhEp-OBPrH2-jK_6tbR-/edit?usp=drive_link"},
{"title": "R102 Employee grievance redressal", "link": "https://docs.google.com/document/d/1qR-Q3da1MxY1tTxMo0OZ52ShPHAmEbWr/edit?usp=drive_link"},
{"title": "R103 Payment of wages", "link": "https://docs.google.com/document/d/1ToZGeZm8VEjp2WHTNLj2MT-mvphO2TAE/edit?usp=drive_link"},
{"title": "R104 Working hours and overtime", "link": "https://docs.google.com/document/d/1Iiugz0lN5HsnU1mr-_hRwpPz1tQ1s6W0/edit?usp=drive_link"},
{"title": "R105 Leave policies", "link": "https://docs.google.com/document/d/1eeekcZcUn8FTSOn2LN6hHQ05tYhnbuNk/edit?usp=drive_link"},
{"title": "R106 Health and safety measures", "link": "https://docs.google.com/document/d/1I8xZOfqBHD0J9I1v6mGi-ZtJh1N_jhKv/edit?usp=drive_link"},
{"title": "R107 Employee benefits and welfare schemes", "link": "https://docs.google.com/document/d/1NVAYGlnSD3QwIzqY_HV6l9m3Efj3S4FO/edit?usp=drive_link"},
{"title": "R108 Termination of employment", "link": "https://docs.google.com/document/d/1ZFdISzgnNhi-VrDAnB23_Zgb8pW9Q89n/edit?usp=drive_link"},
{"title": "R109 Confidentiality and data protection", "link": "https://docs.google.com/document/d/1K2LrYcHeM_JoAi6hIpL8q-JjU5xKfS-9/edit?usp=drive_link"},
{"title": "R110 Workplace harassment policy", "link": "https://docs.google.com/document/d/1U1FL9iGgW8OEirGOqUeQUeQLYg1D28GR/edit?usp=drive_link"},
{"title": "A1 APPENDIX- A1- APPLICATION FOR PERMIT/REGULARISATION", "link": "https://docs.google.com/document/d/1wIeVyrrZVZi9cM9JWS4VyVoaIcgvavSu/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "A1A APPENDIX- A1A-APPLICATION FOR APPROVAL OF THE BUILDING SITE AND FOR THE PERMISSION TO EXECUTE THE WORK", "link": "https://docs.google.com/document/d/1GxHGfW65PuBkb3D8fa-Y5YqnJOvtmCml/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "A1B APPENDIX- A1B  ACKNOWLEDGMENT RECEIPT", "link": "https://docs.google.com/document/d/19x9BRfvMqE4K06OGxREvJJ1Zx3NhoxW3/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "A2 APPENDIX- A2- FORM OF APPLICATION FOR CONSTRUCTION IN PLOTS PARTS OF WHICH HAVE BEEN SURRENDERED FREE OF COST FOR ROAD DEVELOPMENT", "link": "https://docs.google.com/document/d/1u6RilJrQUkimeQkUVo0hripeNctNUe5D/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "A3 APPENDIX -A3- APPLICATION FORM FOR PERMIT FOR DEVELOPMENT/ REDEVELOPMENT OF LAND", "link": "https://docs.google.com/document/d/1BqYcH1qEdAdJqxCDqWR3WAIi0SwtlcPR/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "A4 APPENDIX -A4- APPLICATION FOR LAYOUT APPROVAL AND USAGE OF PLOT/CONCURRENCE", "link": "https://docs.google.com/document/d/1kjM3EUcF2VbkYp__GyAH7K0ZBIbsWmGJ/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "A5 APPENDIX- A5 - APPLICATION FOR INTIMATION FOR THE ERECTION / RE-ERECTION / ALTERATION OF TELECOMMUNICATION TOWERS/TELECOMMUNICATION POLE STRUCTURES/ACCESSORY ROOMS", "link": "https://docs.google.com/document/d/18XNqZ4o5tudBnRjmvhtQ1OnsdK4TWoyj/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "B1 APPENDIX -B1-  DEVELOPMENT PERMIT", "link": "https://docs.google.com/document/d/1wIeVyrrZVZi9cM9JWS4VyVoaIcgvavSu/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "B2 APPENDIX- B2-  SITE APPROVAL AND BUILDING PERMIT", "link": "https://docs.google.com/document/d/1GxHGfW65PuBkb3D8fa-Y5YqnJOvtmCml/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "C APPENDIX- C -  Concurrence / Usage of Plot", "link": "https://docs.google.com/document/d/19x9BRfvMqE4K06OGxREvJJ1Zx3NhoxW3/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "D APPENDIX – D-  NOTICE REGARDING THE INTENTION TO START WORK", "link": "https://docs.google.com/document/d/1u6RilJrQUkimeQkUVo0hripeNctNUe5D/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "E1 APPENDIX -E1-  COMPLETION CERTIFICATE BY THE OWNER", "link": "https://docs.google.com/document/d/1BqYcH1qEdAdJqxCDqWR3WAIi0SwtlcPR/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "E2 APPENDIX -E2-  PARTIAL COMPLETION CERTIFICATE BY THE OWNER", "link": "https://docs.google.com/document/d/1kjM3EUcF2VbkYp__GyAH7K0ZBIbsWmGJ/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "E3 APPENDIX -E3-  COMPLETION 119[REPORT] BY INSTITUTION, ARCHITECT, ENGINEER, ETC.", "link": "https://docs.google.com/document/d/18XNqZ4o5tudBnRjmvhtQ1OnsdK4TWoyj/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "E4 APPENDIX- E4-  PARTIAL COMPLETION 119[REPORT] BY INSTITUTION, ARCHITECT, ENGINEER, ETC.", "link": "https://docs.google.com/document/d/1wIeVyrrZVZi9cM9JWS4VyVoaIcgvavSu/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "F1 APPENDIX -F1-  DEVELOPMENT CERTIFICATE", "link": "https://docs.google.com/document/d/1GxHGfW65PuBkb3D8fa-Y5YqnJOvtmCml/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "F2 APPENDIX -F2-  OCCUPANCY CERTIFICATE OR USE CERTIFICATE", "link": "https://docs.google.com/document/d/19x9BRfvMqE4K06OGxREvJJ1Zx3NhoxW3/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "F2A APPENDIX -F2A OCCUPANCY CERTIFICATE OR USE CERTIFICATE FOR LOW RISK BUILDINGS  CONSTRUCTED BY OBTAINING SELF CERTIFIED BUILDING PERMIT", "link": "https://docs.google.com/document/d/1u6RilJrQUkimeQkUVo0hripeNctNUe5D/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "G1 APPENDIX- G1-  BUILDING CONSTRUCTION/LAND DEVELOPMENT WITHOUT PERMISSION OR DEVIATION FROM APPROVED PLAN- REGULARISATION GRANTED—ORDERS ISSUED", "link": "https://docs.google.com/document/d/1BqYcH1qEdAdJqxCDqWR3WAIi0SwtlcPR/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "G2 APPENDIX –G2-  REGISTER FOR REGULARISED CONSTRUCTIONS", "link": "https://docs.google.com/document/d/1kjM3EUcF2VbkYp__GyAH7K0ZBIbsWmGJ/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "H1B APPENDIX –H1B- Application for Registration as Institution (Architecture) / Institution (Civil Engineering) under the Kerala Municipality Building Rules, 2019", "link": "https://docs.google.com/document/d/18XNqZ4o5tudBnRjmvhtQ1OnsdK4TWoyj/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "H2 APPENDIX –H2- QUALIFICATION AND FUNCTION OF ARCHITECT, ENGINEER, ETC", "link": "https://docs.google.com/document/d/1wIeVyrrZVZi9cM9JWS4VyVoaIcgvavSu/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "H3 APPENDIX –H3-  CERTIFICATE OF REGISTRATION", "link": "https://docs.google.com/document/d/1GxHGfW65PuBkb3D8fa-Y5YqnJOvtmCml/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "I APPENDIX –I-  INSTRUCTIONS TO BE FOLLOWED BY THE APPLICANT", "link": "https://docs.google.com/document/d/19x9BRfvMqE4K06OGxREvJJ1Zx3NhoxW3/edit?usp=sharing&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "J APPENDIX –J-  LIST OF ENCLOSURES", "link": "https://docs.google.com/document/d/1u6RilJrQUkimeQkUVo0hripeNctNUe5D/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "K APPENDIX –K-  130[REQUIREMENTS OF FURNITURE, FIXTURES AND FITTINGS]", "link": "https://docs.google.com/document/d/1BqYcH1qEdAdJqxCDqWR3WAIi0SwtlcPR/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "L APPENDIX –L-  [REQUIREMENTS OF REGULARISATION]", "link": "https://docs.google.com/document/d/1kjM3EUcF2VbkYp__GyAH7K0ZBIbsWmGJ/edit?usp=drive_link&ouid=110217226382874090471&rtpof=true&sd=true"},
{"title": "M APPENDIX- M - CRITERIA FOR CONSIDERING AN APPLICATION FOR EXEMPTION", "link": "https://docs.google.com/document/d/1NxF6tzbh6-tjh_48A-1mOAf53d8ao_Zx/edit?usp=drivesdk&ouid=110217226382874090471&rtpof=true&sd=true"},
    {"title": "N APPENDIX- N - APPLICATION FOR EXEMPTION FROM BUILDING RULES", "link": "https://docs.google.com/document/d/12Tg7iBQPqthVVmFCwOGxz35CX1Ul3L6B/edit?usp=drivesdk&ouid=110217226382874090471&rtpof=true&sd=true"},
    {"title": "O APPENDIX – O - SELF-CERTIFIED BUILDING PERMIT", "link": "https://docs.google.com/document/d/1O8GZALXK9T7uUSXbaHBU4paKJqnlbVSs/edit?usp=drivesdk&ouid=110217226382874090471&rtpof=true&sd=true"},
    {"title": "P APPENDIX – P - Plinth level Inspection Report", "link": "https://docs.google.com/document/d/1Ya_CcWIxN5TbnwyH6Ey7UzsaR5kKiTFk/edit?usp=drivesdk&ouid=110217226382874090471&rtpof=true&sd=true"},
    {"title": "Q APPENDIX – Q - Application for empanelment under the Kerala Municipality Building Rules, 2019", "link": "https://docs.google.com/document/d/1hROcKrkDeH_mgS_N9NzP_Ok1nH_55mPZ/edit?usp=drivesdk&ouid=110217226382874090471&rtpof=true&sd=true"},
    {"title": "SCH I SCHEDULE-I- APPLICATION FEE", "link": "https://docs.google.com/document/d/1d7XcKzBVL5GTyBu-9Ea3sM2QHunuKA8Q/edit?usp=drivesdk&ouid=110217226382874090471&rtpof=true&sd=true"},
    {"title": "SCH II SCHEDULE - II - PERMIT FEE", "link": "https://docs.google.com/document/d/1hIkt99A3rGk5XkRgbxzOuTQvtCz6mBBx/edit?usp=drivesdk&ouid=110217226382874090471&rtpof=true&sd=true"},
    {"title": "SCH III SCHEDULE - III - SCRUTINY FEE FOR LAYOUT APPROVAL", "link": "https://docs.google.com/document/d/1Ya_CcWIxN5TbnwyH6Ey7UzsaR5kKiTFk/edit?usp=drivesdk&ouid=110217226382874090471&rtpof=true&sd=true"}

  ]